### ISSUE TITLE
Cannot generate swagger.json after clean

### ISSUE THREAD

**Issue by ukeshava** [zhurlik/swagger-gradle-example#1]
When performing gradle clean and then gradle swagger a ClassNotFoundException is thrown. If gradle swagger is then run again (basically after the api build is done in previous run), it works fine.

build.gradle looks as below:

[buildscript {
repositories {
maven { url mavenRepo }
maven { url pluginsRepo }
}
dependencies {
    classpath "com.github.kongchen:swagger-maven-plugin:3.1.4"
    classpath files(project(':api').configurations['runtime'].files)
    classpath files(project(':api').sourceSets['main'].output)
}
}

import com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo
import com.github.kongchen.swagger.docgen.mavenplugin.ApiSource
import io.swagger.models.Info

task swagger(dependsOn: ':api:build') {
doLast {
println 'Swagger GenDoc...'
project.file(reportsDir).mkdirs()

    // a trick to have all needed classes in the classpath
    def classLoader = new GroovyClassLoader()

    buildscript.configurations.classpath.each {
        classLoader.addURL(it.toURI().toURL())
    }

    // the same settings as in the swagger-maven-example/pom.xml
    final ApiDocumentMojo mavenTask = Class.forName('com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo', true, classLoader).newInstance(
            apiSources: [
                    new ApiSource(
                            springmvc: false,
                            locations: [<location>],
                            schemes: ['http', 'https'],
                            host: '<host>',
                            basePath: '/api',
                            info: new Info(
                                    title: "REST APIs",
                                    version: 'v1',
                                    description: "REST APIs",
                            ),
                            swaggerDirectory: reportsDir
                    )
            ]
    )
    mavenTask.execute()
    println 'Swagger GenDoc task is completed'
}
}

**Comment by zhurlik** [comment]
Hi, 
Thanks, I will check it next week.

**Comment by zhurlik** [comment]
@ukeshava Hi, I have looked at this issue and after quick researching I found the following
[link](https://discuss.gradle.org/t/buildscript-classpath-dependencies-do-not-seem-to-get-loaded-on-first-run-after-gradle-clean/9932). As I understand it means that there is no easy way to do it, because buildscript block doesn't make the 'api' project even if it was added into classpath in the dependencies.

I can try to figure out how to move the reference to classes from buildscript to another place to be able to add them into swagger classloader.

**Comment by ukeshava** [comment]
Thank you very much for your time and help. Do you think using any wrapper
might help? I'm gradle novice so wanted to hear it from an expert to make
sure I haven't missed anything.

Thanks for your response, really appreciate it
Regards
Usha

**Comment by ukeshava** [comment]
I think I did not read through carefully enough. I did remove the
dependencies from buildscript and put it in outer block that did not help
either. Also tried to use directory instead of files during resolution. It
does perform api build as I see it running but somehow misses the classes.
In debug log in the list of urls that rejections scan the API build path is
missing.

However if I try to print class loader classpath or print directory
structure of API build folder after custom class loader is set, it does so
successfully. So, kind of confused why it doesn't work.

Regards
Usha

On Jul 11, 2017 3:21 AM, "Uladzimir Zhuraulevich" <notifications@github.com>
wrote:

@ukeshava <https://github.com/ukeshava> Hi, I have looked at this issue and
after quick researching I found the following
link
<https://discuss.gradle.org/t/buildscript-classpath-dependencies-do-not-seem-to-get-loaded-on-first-run-after-gradle-clean/9932>.
As I understand it means that there is no easy way to do it, because
buildscript block doesn't make the 'api' project even if it was added into
classpath in the dependencies.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/zhurlik/swagger-gradle-example/issues/1#issuecomment-314260225>,
or mute the thread

**Comment by zhurlik** [comment]
@ukeshava Looks like I found [the fix](https://github.com/zhurlik/swagger-gradle-example/commit/3f95d8e4dd706e790b2bef4183baa8993acfff60)
Could you check if it works for you.
Thanks

**Comment by ukeshava** [comment]
Thanks so much, will try it out. I was trying with classpath but did not
know how to access the classloader.

Regards
Usha

On Jul 11, 2017 9:59 PM, "Uladzimir Zhuraulevich" <notifications@github.com>
wrote:

@ukeshava <https://github.com/ukeshava> Looks like I found the fix
<https://github.com/zhurlik/swagger-gradle-example/commit/3f95d8e4dd706e790b2bef4183baa8993acfff60>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zhurlik/swagger-gradle-example/issues/1#issuecomment-314499476>,
or mute the thread

**Comment by zhurlik** [comment]
@ukeshava I have created a simple gradle plugin
https://github.com/zhurlik/gradle-swagger-plugin
https://plugins.gradle.org/plugin/com.github.zhurlik.swagger

**Comment by ukeshava** [comment]
Sure will take a look.

Thank you Sooooo much for the fix, it worked well. This is what I used:

buildscript {
    repositories {
        maven { url mavenRepo }
    }
    dependencies {
        classpath "com.github.kongchen:swagger-maven-plugin:3.1.4"
    }
}

import com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo
import com.github.kongchen.swagger.docgen.mavenplugin.ApiSource
import io.swagger.models.Info


task swagger(dependsOn: ':api:build') {
    doLast {
        println 'Swagger GenDoc...'
        project.file(<dir>).mkdirs()

        FileCollection apiRuntimeFiles =
files(project(':api').configurations['runtime'].files)
        apiRuntimeFiles.each {
            buildscript.classLoader.addURL(it.toURI().toURL())
        }

        FileCollection apiClassFiles
=files(project(':api').sourceSets['main'].output)
        apiClassFiles.each {
            buildscript.classLoader.addURL(it.toURI().toURL())
        }

        final ApiDocumentMojo mavenTask =
Class.forName('com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo',
true, buildscript.classLoader).newInstance(
                apiSources: [
                        new ApiSource(
                                springmvc: false,
                                locations: ['<loc>'],
                                schemes: ['http', 'https'],
                                host: '<host>',
                                basePath: '/api',
                                info: new Info(
                                        title: "REST API's",
                                        version: 'v1',
                                        description: "REST API's",
                                ),
                                swaggerDirectory: <dir>
                        )
                ]
        )
        mavenTask.execute()
        println 'Swagger GenDoc task is completed'
    }
}

**Comment by zhurlik** [comment]
@ukeshava You can simplify it via using the custom gradle plugin
See https://github.com/zhurlik/gradle-swagger-plugin

**Comment by ukeshava** [comment]
okay, will take a look.

Thanks!

**Comment by zhurlik** [comment]
@ukeshava looks like the issue can be closed

**Comment by ukeshava** [comment]
sure, closing the issue.

Regards
Usha
